avahtrans/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('shipment/', include('shipment.urls', namespace='shipment')),
]

frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),    
    path('about/', views.AboutView.as_view(), name='about'),    
    path('contact/', views.ContactView.as_view(), name='contact'),    
    path('tracking/', views.TrackingView, name='tracking'),    
]

shipment/urls.py
from django.urls import path
from . import views

app_name = 'shipment'

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),

    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('add_shipment/', views.CreateShipmentView.as_view(), name='add_shipment'),
    path('update_shipment/<pk>/', views.update_shipment, name='update_shipment'),
    path('delete_shipment/<pk>/', views.delete_shipment, name='delete_shipment'),

    # neph side
    path('n_dashboard/', views.NDashboardView.as_view(), name='n_dashboard'),
    path('add_package/', views.NCreateShipmentView.as_view(), name='add_package'),
    path('update_package/<pk>/', views.update_package, name='update_package'),
    path('delete_package/<pk>/', views.delete_package, name='delete_package'),
]

templates/package/add_package.html
{% extends './base.html' %}

{% load static %}

{% block sub_content %}
<div class="row align-item-center justify-content-center">
    <div class="col-md-10">
        <div class="card shadow card-sm bg-secondary text-white">
            <h3 class="card-title text-center text-success py-3">Add a new package</h3>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
            <div class="card-body">
                <form action="." method="POST">
                    {% csrf_token %}

                    {% if form.errors %}
                        <p class="text-white fw-bold">Please correct the following errors:</p>
                        {% for field in form %}
                            {% if field.errors %}
                            <div class="alert alert-primary" role="alert">
                                {{ field.label }}: {{ field.errors|striptags }}
                            </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    
                    <div class="row">
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.sender_name.id_for_label}}" class="form-label fw-bold text-light">Sender Name:</label>
                                {{form.sender_name}}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.sender_nationality.id_for_label}}" class="form-label fw-bold text-light">Sender Nationality:</label>
                                {{form.sender_nationality}}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.sender_location.id_for_label}}" class="form-label fw-bold text-light">Sender Location:</label>
                                {{form.sender_location}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="{{ form.receiverr_name.id_for_label}}" class="form-label fw-bold text-light">Receiver Name:</label>
                                {{form.receiver_name}}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="{{ form.receiver_email.id_for_label}}" class="form-label fw-bold text-light">Receiver Email:</label>
                                {{form.receiver_email}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="mb-3">
                                <label for="{{ form.receiverr_address.id_for_label}}" class="form-label fw-bold text-light">Receiver Address:</label>
                                {{form.receiver_address}}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.receiver_phone.id_for_label}}" class="form-label fw-bold text-light">Receiver Phone:</label>
                                {{form.receiver_phone}}
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.weight.id_for_label}}" class="form-label fw-bold text-light">Weight:</label>
                                {{form.weight}}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.status.id_for_label}}" class="form-label fw-bold text-light">Status:</label>
                                {{form.status}}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.shipment_location.id_for_label}}" class="form-label fw-bold text-light">Shipment Location:</label>
                                {{form.shipment_location}}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.comment.id_for_label}}" class="form-label fw-bold text-light">Comment:</label>
                        {{form.comment}}
                    </div>

                    <input type="submit" class="btn btn-secondary fw-bold w-100 text-white" value="Submit">                
                </form>
                
            </div>
        </div>
    </div>
    
</div>
{% endblock %}

templates/package/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AvahTrans | Best delivery network</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/shipment.css' %}">
  </head>

  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'images/site.webmanifest' %}">
  <body class="bg-dark">
    {% include './navbar.html' %}
    {% block content %} 
    
      <div class="container py-5">
        {% block sub_content %}
        {% endblock %}
      </div>
   
    {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

templates/package/n_dashboard.html
{% extends './base.html' %}

{% load static %}

{% block sub_content %}
<div class="row">
    <div class="col-md-12">
        <div class="card shadow card-sm bg-secondary text-white">
          {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
            <div class="card-body">
                <table class="table text-light  table-borderless table-sm">
                    <thead class="text-success">
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Sender Name</th>
                        <th scope="col">Receiver Name</th>
                        <th scope="col">Receiver Email</th>
                        <th scope="col">Status</th>
                        <th scope="col">Tracking Code</th>
                        <th scope="col">Date Created</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    {% for shipment in packages %}
                    <tbody>
                      <tr>
                        <th scope="row">{{forloop.counter}}.</th>
                        <td >{{shipment.sender_name}}</td>
                        <td>{{shipment.receiver_name}}</td>
                        <td>{{shipment.receiver_email}}</td>
                        <td class="text-info"><strong>{{shipment.status}}</strong></td>
                        <td><strong>{{shipment.tracking_number}}</strong> </td>
                        <td>{{shipment.created}}</td>
                        <td><a href="{% url 'shipment:update_package' shipment.id %}" class="btn btn-info btn-sm fw-bold text-white">Update</a></td>
                        <td><a href="{% url 'shipment:delete_package' shipment.id %}" class="btn btn-danger btn-sm fw-bold">Delete</a></td>
                      </tr>
                    </tbody>
                    {% endfor %}
                  </table>
                  <!-- <nav aria-label="Page navigation example">
                    <ul class="pagination">
                      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                      <li class="page-item"><a class="page-link" href="#">1</a></li>
                      <li class="page-item"><a class="page-link" href="#">2</a></li>
                      <li class="page-item"><a class="page-link" href="#">3</a></li>
                      <li class="page-item"><a class="page-link" href="#">Next</a></li>
                    </ul>
                  </nav> -->
                  <!-- pagination -->
                  <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                
                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
    <!-- <div class="col-md-2">
        <div class="card shadow-lg bg-secondary text-white">
            <h1>hi world</h1>
        </div>
    </div> -->
</div>
{% endblock %}

templates/package/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg  bg-dark navbar-dark shadow">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'shipment:dashboard' %}"><img src="{% static 'images/logo.png' %}" alt="logo" style="width: 200px; "></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
        <div class="navbar-nav mx-auto">
          <a class="nav-link" href="{% url 'shipment:n_dashboard' %}">Dashboard</a>
          <a class="nav-link" href="{% url 'shipment:add_package' %}">Add package</a>
          <a class="nav-link" href="{% url 'shipment:logout' %}">Sign Out</a>
        </div>
      </div>
    </div>
</nav>

templates/package/update_package.html
{% extends './base.html' %}

{% load static %}

{% block sub_content %}
<div class="row align-item-center justify-content-center">
    <div class="col-md-10">
        <div class="card shadow card-sm bg-secondary text-white">
            <h3 class="card-title text-center text-success py-3">Update a Package Details</h3>
            
            <div class="card-body">
                <form action="." method="POST">
                    {% csrf_token %}

                    {% if form.errors %}
                        <p class="text-white fw-bold">Please correct the following errors:</p>
                        {% for field in form %}
                            {% if field.errors %}
                            <div class="alert alert-primary" role="alert">
                                {{ field.label }}: {{ field.errors|striptags }}
                            </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    
                    <div class="row">
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.sender_name.id_for_label}}" class="form-label fw-bold text-light">Sender Name:</label>
                                {{form.sender_name}}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.sender_nationality.id_for_label}}" class="form-label fw-bold text-light">Sender Nationality:</label>
                                {{form.sender_nationality}}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.sender_location.id_for_label}}" class="form-label fw-bold text-light">Sender Location:</label>
                                {{form.sender_location}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="{{ form.receiverr_name.id_for_label}}" class="form-label fw-bold text-light">Receiver Name:</label>
                                {{form.receiver_name}}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="{{ form.receiver_email.id_for_label}}" class="form-label fw-bold text-light">Receiver Email:</label>
                                {{form.receiver_email}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="mb-3">
                                <label for="{{ form.receiverr_address.id_for_label}}" class="form-label fw-bold text-light">Receiver Address:</label>
                                {{form.receiver_address}}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.receiver_phone.id_for_label}}" class="form-label fw-bold text-light">Receiver Phone:</label>
                                {{form.receiver_phone}}
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.weight.id_for_label}}" class="form-label fw-bold text-light">Weight:</label>
                                {{form.weight}}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.status.id_for_label}}" class="form-label fw-bold text-light">Status:</label>
                                {{form.status}}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="{{ form.shipment_location.id_for_label}}" class="form-label fw-bold text-light">Shipment Location:</label>
                                {{form.shipment_location}}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.comment.id_for_label}}" class="form-label fw-bold text-light">Comment:</label>
                        {{form.comment}}
                    </div>

                    <input type="submit" class="btn btn-secondary fw-bold w-100 text-white" value="Submit">                
                </form>
                
            </div>
        </div>
    </div>
    
</div>
{% endblock %}