avahtrans/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('shipment/', include('shipment.urls', namespace='shipment')),
]

frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),    
    path('about/', views.AboutView.as_view(), name='about'),    
    path('contact/', views.ContactView.as_view(), name='contact'),    
    path('tracking/', views.TrackingView, name='tracking'),    
]

shipment/urls.py
from django.urls import path
from . import views

app_name = 'shipment'

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),

    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('add_shipment/', views.CreateShipmentView.as_view(), name='add_shipment'),
    path('update_shipment/<pk>/', views.update_shipment, name='update_shipment'),
    path('delete_shipment/<pk>/', views.delete_shipment, name='delete_shipment'),

    # neph side
    path('n_dashboard/', views.NDashboardView.as_view(), name='n_dashboard'),
    path('add_package/', views.NCreateShipmentView.as_view(), name='add_package'),
    path('update_package/<pk>/', views.update_package, name='update_package'),
    path('delete_package/<pk>/', views.delete_package, name='delete_package'),
]

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.contrib import messages
from django.db.models import Q

from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.core.mail import send_mail


from shipment.models import Shipment, Package

class HomeView(TemplateView):
    template_name = 'frontend/index.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.is_staff:
                return HttpResponseRedirect(reverse_lazy('shipment:n_dashboard'))
            else:
                return HttpResponseRedirect(reverse_lazy('shipment:dashboard'))
        return super().dispatch(request, *args, **kwargs)


class AboutView(TemplateView):
    template_name = 'frontend/about.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.is_staff:
                return HttpResponseRedirect(reverse_lazy('shipment:n_dashboard'))
            else:
                return HttpResponseRedirect(reverse_lazy('shipment:dashboard'))
        return super().dispatch(request, *args, **kwargs)

class ContactView(TemplateView):
    template_name = 'frontend/contact.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.is_staff:
                return HttpResponseRedirect(reverse_lazy('shipment:n_dashboard'))
            else:
                return HttpResponseRedirect(reverse_lazy('shipment:dashboard'))
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        print(subject)
        try:
            send_mail(
                'Message From '+name+' <'+email+'>',
                message,
                'info@avahtrans.com',
                ['info@avahtrans.com'],
                fail_silently=False,
            )
            messages.success(request, 'Email sent successfully, we will get back to you as soon as possible')
        except:
            messages.error(request, 'There was an error while trying to send your email, please try again')

        finally:
            return HttpResponseRedirect(reverse_lazy('frontend:contact'))


def TrackingView(request):
    if request.method == 'POST':
        tracking_code = request.POST.get('tracking_code')
        shipments = Shipment.objects.filter(tracking_number=tracking_code).union(Package.objects.filter(tracking_number=tracking_code) )
          
        
        if shipments.exists():
            return render(request, 'frontend/tracking.html', {'shipments':shipments}) 
        else:
            messages.error(request, "Invalid tracking code. Please check the code and try again. please make sure no spaces in between the letters")
            return redirect('frontend:home')
    return redirect('frontend:home')
    # return render(request, 'frontend/tracking.html') 

templates/frontend/about.html
{% extends './f_base.html' %}

{% load static %}

{% block content %}
<!-- Header Start -->
<div class="jumbotron jumbotron-fluid mb-5">
    <div class="container text-center py-5">
        <h1 class="text-white display-3">About</h1>
        <div class="d-inline-flex align-items-center text-white">
            <p class="m-0"><a class="text-white" href="">Home</a></p>
            <i class="fa fa-circle px-3"></i>
            <p class="m-0">About</p>
        </div>
    </div>
</div>
<!-- Header End -->

<!-- About Start -->
<div class="container-fluid py-5">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 pb-4 pb-lg-0">
                <img class="img-fluid w-100" src="{% static 'frontend/img/about.jpg' %}" alt="">
                <div class="bg-primary text-dark text-center p-4">
                    <h3 class="m-0">25+ Years Experience</h3>
                </div>
            </div>
            <div class="col-lg-7">
                <h6 class="text-primar text-uppercase font-weight-bold">About Us</h6>
                <h1 class="mb-4">Trusted & Faster Logistic Service Provider</h1>
                <p class="mb-4">Customer First is about removing friction. People Led is our employee experience. And Innovation Driven is the value we create for shareowners,
                 We are guided by leaders who constantly inspire us. We believe everyone has the power to make an impact and by serving others, you serve the collective good, moving everyone forward.
                </p>
                <div class="d-flex align-items-center pt-2">
                    <button type="button" class="btn-play" data-toggle="modal"
                        data-src="https://www.youtube.com/embed/DWRcNpR6Kdc" data-target="#videoModal">
                        <span></span>
                    </button>
                    <h5 class="font-weight-bold m-0 ml-4">Play Video</h5>
                </div>
            </div>
        </div>
    </div>
    <!-- Video Modal -->
    <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>        
                    <!-- 16:9 aspect ratio -->
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="" id="video"  allowscriptaccess="always" allow="autoplay"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About End -->

<!-- Features Start -->
<div class="container-fluid bg-secondary my-5">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5">
                <img class="img-fluid w-100" src="{% static 'frontend/img/feature.jpg' %}" alt="">
            </div>
            <div class="col-lg-7 py-5 py-lg-0">
                <h6 class="text-primar text-uppercase font-weight-bold">Why Choose Us</h6>
                <h1 class="mb-4">Faster, Safe and Trusted Logistics Services</h1>
                <p class="mb-4">If you’re shipping air freight, it’s critical. Our International and North American Air Freight services offers day-specific, door-to-door service to 220+ countries.</p>
                <ul class="list-inline">
                    <li><h6><i class="far fa-dot-circle text-primary mr-3"></i>Best In Industry</h6>
                    <li><h6><i class="far fa-dot-circle text-primary mr-3"></i>Emergency Services</h6></li>
                    <li><h6><i class="far fa-dot-circle text-primary mr-3"></i>24/7 Customer Support</h6></li>
                </ul>
                <a href="" class="btn btn-primary mt-3 py-2 px-4">Learn More</a>
            </div>
        </div>
    </div>
</div>
<!-- Features End -->

<!-- Team Start -->
<div class="container-fluid pt-5">
    <div class="container">
        <div class="text-center pb-2">
            <h6 class="text-primary text-uppercase font-weight-bold">Delivery Team</h6>
            <h1 class="mb-4">Meet Our Delivery Team</h1>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="team card position-relative overflow-hidden border-0 mb-5">
                    <img class="card-img-top" src="{% static 'frontend/img/team-1.jpg' %}" alt="">
                    <div class="card-body text-center p-0">
                        <div class="team-text d-flex flex-column justify-content-center bg-secondary">
                            <h5 class="font-weight-bold">Christopher Smith</h5>
                            <span>Ware House Manager</span>
                        </div>
                        <div class="team-social d-flex align-items-center justify-content-center bg-primary">
                            <a class="btn btn-outline-dark btn-social mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-dark btn-social mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-dark btn-social mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-outline-dark btn-social" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="team card position-relative overflow-hidden border-0 mb-5">
                    <img class="card-img-top" src="{% static 'frontend/img/team-2.jpg' %}" alt="">
                    <div class="card-body text-center p-0">
                        <div class="team-text d-flex flex-column justify-content-center bg-secondary">
                            <h5 class="font-weight-bold">Robert Williams</h5>
                            <span>Supervisor</span>
                        </div>
                        <div class="team-social d-flex align-items-center justify-content-center bg-primary">
                            <a class="btn btn-outline-dark btn-social mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-dark btn-social mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-dark btn-social mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-outline-dark btn-social" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="team card position-relative overflow-hidden border-0 mb-5">
                    <img class="card-img-top" src="{% static 'frontend/img/team-3.jpg' %}" alt="">
                    <div class="card-body text-center p-0">
                        <div class="team-text d-flex flex-column justify-content-center bg-secondary">
                            <h5 class="font-weight-bold">Laura Martins</h5>
                            <span>Supervisor</span>
                        </div>
                        <div class="team-social d-flex align-items-center justify-content-center bg-primary">
                            <a class="btn btn-outline-dark btn-social mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-dark btn-social mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-dark btn-social mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-outline-dark btn-social" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="team card position-relative overflow-hidden border-0 mb-5">
                    <img class="card-img-top" src="{% static 'frontend/img/team-4.jpg' %}" alt="">
                    <div class="card-body text-center p-0">
                        <div class="team-text d-flex flex-column justify-content-center bg-secondary">
                            <h5 class="font-weight-bold">Clerk Johnson</h5>
                            <span>Branch Manager</span>
                        </div>
                        <div class="team-social d-flex align-items-center justify-content-center bg-primary">
                            <a class="btn btn-outline-dark btn-social mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-dark btn-social mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-dark btn-social mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-outline-dark btn-social" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Team End -->
{% endblock %}

templates/frontend/contact.html
{% extends './f_base.html' %}

{% load static %}

{% block content %}
<!-- Header Start -->
<div class="jumbotron jumbotron-fluid mb-5">
    <div class="container text-center py-5">
        <h1 class="text-white display-3">Contact</h1>
        <div class="d-inline-flex align-items-center text-white">
            <p class="m-0"><a class="text-white" href="">Home</a></p>
            <i class="fa fa-circle px-3"></i>
            <p class="m-0">Contact</p>
        </div>
    </div>
</div>
<!-- Header End -->

<!-- Contact Start -->
<div class="container-fluid py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 pb-4 pb-lg-0">
                <div class="card shadow">
                    <div class="card-body">
                        <p><strong>US Office:</strong> Americas Tower, 1177 6th Ave, New York, NY 10036, USA <br>
                        <strong>Phone:</strong>+1 (516) 888-5354</p>
                        <p><strong>UK Office:</strong> 4 Upper Montagu St, London W1H 2AG, United Kingdom <br>
                        <strong>Phone:</strong>+44 7418 397914</p>
                    </div>
                </div>
                <div class="bg-primary text-dark text-center p-4">
                    <h4 class="m-0"><i class="fa fa-map-marker-alt text-white mr-2"></i>Email: info@avahtrans.com</h4>
                </div>
                <iframe style="width: 100%; height: 470px;"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                    frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
            <div class="col-lg-7">
                <h6 class="text-primar text-uppercase font-weight-bold">Contact Us</h6>
                <h1 class="mb-4">Contact For Any Queries</h1>

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{message}}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}

                <div class="contact-form bg-secondary" style="padding: 30px;">
                    <div id="success"></div>
                    <form method="POST" action=".">
                        {% csrf_token %}
                        <div class="control-group">
                            <input type="text" class="form-control border-0 p-4" id="name" name="name" placeholder="Your Name"
                                required="required" data-validation-required-message="Please enter your name" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input type="email" class="form-control border-0 p-4" id="email" name="email" placeholder="Your Email"
                                required="required" data-validation-required-message="Please enter your email" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input type="text" class="form-control border-0 p-4" name="subject" id="subject" placeholder="Subject"
                                required="required" data-validation-required-message="Please enter a subject" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <textarea class="form-control border-0 py-3 px-4" rows="3" name="message" id="message" placeholder="Message"
                                required="required"
                                data-validation-required-message="Please enter your message"></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div>
                            <button class="btn btn-primary py-3 px-4" type="submit">Send
                                Message</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->
{% endblock %}

templates/frontend/f_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>AvahTrans - Best delivery Company</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <!-- <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description"> -->

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'frontend/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'frontend/css/style.css' %}" rel="stylesheet">

    <style>
        .logo-neph{
            width: 240px;
        }
        @media (max-width: 780px) {
            .logo-neph{
                width: 180px;
            }
        }
    </style>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/site.webmanifest' %}">
</head>

<body>
    {% include './navbar.html' %}
    {% block content %}
    {% endblock %}
    {% include './footer.html' %}
    
    <script type="text/javascript"
    src=
    "https://translate.google.com/translate_a/element.js?
    cb=googleTranslateElementInit">
    </script>

    <!-- google translate -->
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement(
                {pageLanguage: 'en'},
                'google_translate_element'
            );
        }
    </script>

    

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'frontend/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'frontend/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'frontend/lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'frontend/lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'frontend/mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'frontend/mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'frontend/js/main.js' %}"></script>

    
</body>

</html>

templates/frontend/footer.html
<!-- Footer Start -->
<div class="container-fluid bg-dark text-white mt-5 py-5 px-sm-3 px-md-5">
    <div class="row pt-5">
        <div class="col-lg-7 col-md-6">
            <div class="row">
                <div class="col-md-6 mb-5">
                    <h3 class="text-primar mb-4">Get In Touch</h3>
                    <p><i class="fa fa-map-marker-alt mr-2"></i>United States | United Kingdom</p>
                    <p><i class="fa fa-phone-alt mr-2"></i>US +15168885354 | UK +447418397914</p>
                    <p><i class="fa fa-envelope mr-2"></i>deliveries@avahtrans.com</p>
                    <div class="d-flex justify-content-start mt-4">
                        <a class="btn btn-outline-light btn-social mr-2" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-light btn-social" href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
                <div class="col-md-6 mb-5">
                    <h3 class="text-primar mb-4">Quick Links</h3>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-white mb-2" href="{% url 'frontend:home' %}"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-white mb-2" href="{% url 'frontend:about' %}"><i class="fa fa-angle-right mr-2"></i>About Us</a>
                        <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Services</a>
                        <!-- <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Pricing Plan</a> -->
                        <a class="text-white" href="{% url 'frontend:contact' %}"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-5 col-md-6 mb-5">
            <h3 class="text-primar mb-4">Newsletter</h3>
            <p>Please sign up here to get our latest updates and promotion informations. clients who sign up always have a better chance</p>
            <div class="w-100">
                <div class="input-group">
                    <input type="text" class="form-control border-light" style="padding: 30px;" placeholder="Your Email Address">
                    <div class="input-group-append">
                        <button class="btn btn-primary px-4">Sign Up</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid bg-dark text-white border-top py-4 px-sm-3 px-md-5" style="border-color: #3E3E4E !important;">
    <div class="row">
        <div class="col-lg-6 text-center text-md-left mb-3 mb-md-0">
            <p class="m-0 text-white">&copy; <a href="#">AvahTrans Logistics</a>.  All Rights Reserved. 
            
            </p>
        </div>
        <div class="col-lg-6 text-center text-md-right">
            <ul class="nav d-inline-flex">
                <li class="nav-item">
                    <a class="nav-link text-white py-0" href="#">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white py-0" href="#">Terms</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white py-0" href="#">FAQs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white py-0" href="#">Help</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

templates/frontend/login.html
{% extends './f_base.html' %}

{% load static %}

{% block content %}
<!-- Header Start -->
<div class="container py-5">
    <div class="row align-item-center justify-content-center">
        <div class="col-md-5">
            <div class="card shadow">
                <h3 class="text-center text-info py-3">Login Admin</h3>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{message}}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="card-body">
                    <form action="{% url 'shipment:login' %}" method="POST">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="username" class="form-label fw-bold text-dark">Username:</label>
                            <input name="username" type="text" class="form-control" id="username" placeholder="Enter Username" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label fw-bold text-dark">Password:</label>
                            <input name="password" type="password" class="form-control" id="password" placeholder="Enter Password" required>
                        </div>
                        <input type="submit" class="btn btn-primary fw-bold w-100" value="Login" >
                          
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Header End -->



{% endblock %}

templates/frontend/navbar.html
{% load static %}

<!-- Topbar Start -->
<div class="container-fluid bg-dark">
    <div class="row py-2 px-lg-5">
        <div class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">
            <div class="d-inline-flex align-items-center text-white">
                <small><i class="fa fa-phone-alt mr-2"></i>+15168885354</small>
                <small class="px-3">|</small>
                <small><i class="fa fa-envelope mr-2"></i>deliveries@avahtrans.com</small>
            </div>
        </div>
        <!-- <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <a class="text-white px-2" href="">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a class="text-white px-2" href="">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="text-white px-2" href="">
                    <i class="fab fa-linkedin-in"></i>
                </a>
                <a class="text-white px-2" href="">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="text-white pl-2" href="">
                    <i class="fab fa-youtube"></i>
                </a>
            </div>
        </div> -->
    </div>
</div>
<!-- Topbar End -->


<!-- Navbar Start -->
<div class="container-fluid p-0">
    <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-lg-5">
        <a href="{% url 'frontend:home' %}" class="navbar-brand ml-lg-3">
            <img src="{% static 'images/logo1.png' %}" class="logo-neph" alt="logo">
            <!-- <h1 class="m-0 display-5 text-uppercase text-primary"><i class="fa fa-truck mr-2"></i>Faster</h1> -->
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between px-lg-3" id="navbarCollapse">
            <div class="navbar-nav m-auto py-0">
                <a href="{% url 'frontend:home' %}" class="nav-item nav-link active">Home</a>
                <a href="{% url 'frontend:about' %}" class="nav-item nav-link">About</a>
                <!-- <a href="service.html" class="nav-item nav-link">Service</a> -->
                <!-- <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu rounded-0 m-0">
                        <a href="blog.html" class="dropdown-item">Blog Grid</a>
                        <a href="single.html" class="dropdown-item">Blog Detail</a>
                    </div>
                </div> -->
                <a href="{% url 'frontend:contact' %}" class="nav-item nav-link">Contact</a>
                <a href="{% url 'shipment:login' %}" class="nav-item nav-link">Login</a>
            </div>
            
            <a href="" class="btn btn-primary py-2 px-4 d-none d-lg-block"><div id="google_translate_element"></div></a>
        </div>
    </nav>
</div>
<!-- Navbar End -->